- hosts: web
  tasks:
    - name: install pip and python 2
      raw: test -e /usr/bin/pip2 || (apt -y update && apt install -y python-pip)
      become: true

    - name: remove python3-pip
      apt:
        name: python3-pip
        state: absent
      become: yes

    - name: Install packages
      apt:
        name:
          - redis-server
          - python3-cryptography
          - python3-pip
          - python-bs4
          - python-lxml
          - python-requests
          - openvpn
          - libmysqlclient-dev
          - libffi-dev
        state: latest
        update_cache: yes
      become: yes

- hosts: web
  tasks:
    - user:
        name: ctf
      become: True

    - name: set timezone to UTC
      timezone:
        name: UTC
      become: yes

    - file: path=/srv/ctf state=directory
      become: yes

    - name: sync project to container when not dev system
      synchronize:
        src: ./
        dest: /srv/ctf
        use_ssh_args: yes
      when: in_vagrant is not defined
      become: yes

- hosts: ctfserver
  tasks:

    - name: configure lxd to mount vagrant dir for development (subuid file)
      lineinfile:
        path: /etc/subuid
        line: "root:1000:1"
      when: in_vagrant is defined
      become: yes

    - name: configure lxd to mount vagrant dir for development (subgid file)
      lineinfile:
        path: /etc/subgid
        line: "root:1000:1"
      when: in_vagrant is defined
      become: yes

    - name: configure lxd to mount vagrant dir for development (raw.idmap)
      command: lxc config set web raw.idmap "both 1000 1001"
      when: in_vagrant is defined
      become: yes

    - name: restart webcontainer
      command: lxc restart web
      when: in_vagrant is defined
      become: yes

    - name: configure lxd to mount vagrant dir for development (bind mount)
      command: lxc config device add web vagrant disk source=/vagrant path=/srv/ctf
      when: in_vagrant is defined
      ignore_errors: yes
      become: yes

- hosts: web
  tasks:

    - name: Create a symbolic link
      file:
        src: /srv/ctf/ctfdbapi
        dest: /opt/ctfdbapi
        state: link
      become: yes

    - name: Create a symbolic link
      file:
        src: /srv/ctf/scorebot
        dest: /opt/scorebot
        state: link
      become: yes

    - name: log dir
      file:
        path: /var/log/ctf/
        state: directory
        owner: ctf
        group: ctf
        recurse: true
      become: yes


    - service: name=redis-server state=started



    - name: install requirements for cryptography
      apt:
        name:
          - python3-dev
          - libffi-dev
          - libssl-dev
          - build-essential
      become: yes



    - name: Install requirements
      pip:
        requirements: /opt/ctfdbapi/requirements.txt
        executable: pip3
        #virtualenv: /home/{{role_path|basename}}/env
        #virtualenv_python: python3
      become: yes






    - name: set owner/group for service files
      file:
        path: "/srv/ctf"
        owner: "ctf"
        group: "ctf"
        recurse: yes
      become: yes

- hosts: web
  roles:
    - mariadb
  #- scorebot_deps_2019
