- hosts: localhost
  tasks:
    - name: assert that we are using vagrant for this playbook
      assert:
        that: in_vagrant is defined

    - name: install yaml for python
      apt:
        name:
          - python-yaml
          - python3-yaml
        state: latest
        update_cache: yes
      become: yes

    - name: ansible-galaxy requirements
      command: ansible-galaxy install -r /vagrant/requirements.yml --force
      become: yes

    - name: permissions vagrant/ansible path
      file:
        path: "{{ item }}"
        owner: vagrant
        group: vagrant
        mode: '0555'
      loop:
        - /vagrant/ansible
      become: yes

    - name: permissions for inventory script
      file:
        path: /vagrant/inventories/ctf.py
        mode: '0777'
      become: yes