- name: Host allow new wireguard conections
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: "42{{ '%03d'|format(hostvars[item]['team_num']|int) }}"
    ctstate: NEW
    jump: ACCEPT
  become: yes
  loop: "{{ groups['ad_containers'] }}"

- name: Host allow new wireguard conections (also for admin team 254)
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: "42254"
    ctstate: NEW
    jump: ACCEPT
  become: yes