api_secret: qGoOz7TMjp7QkS16qaR9ARpuiC40YgAQ
dashboard_admin_password: 0Gy6y6KCHqIK8N2mD8kyaWIyBzYY4GNT
lxd_trust_pw: VFiMJ9FWxlTFL5uMV2P2VP3wvEaqGkM0
mysql_ctf_password: AJ5OLPsJ3UmNGhjNeBDwAQ7mNKvhN1Mg
mysql_root_password: 1vQuuHdLzpPh3e95YwB8STpxbQ12CBnt
secret: ZICprmxHy7Mflf5Ah4uIi5HTMjUX4mCB
team_count: 2
